-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 08:11:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TrainSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrainSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrainSystem` DEFAULT CHARACTER SET utf8 ;
USE `TrainSystem` ;

-- -----------------------------------------------------
-- Table `TrainSystem`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainSystem`.`train` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `power` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainSystem`.`human`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainSystem`.`human` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `passport` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainSystem`.`crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainSystem`.`crew` (
  `id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  `train_id` INT NOT NULL,
  `human_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_crew_train_idx` (`train_id` ASC) VISIBLE,
  INDEX `fk_crew_human1_idx` (`human_id` ASC) VISIBLE,
  CONSTRAINT `fk_crew_train`
    FOREIGN KEY (`train_id`)
    REFERENCES `TrainSystem`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crew_human1`
    FOREIGN KEY (`human_id`)
    REFERENCES `TrainSystem`.`human` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainSystem`.`carriage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainSystem`.`carriage` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `weight` INT NULL,
  `height` INT NULL,
  `maxPassengers` INT NULL,
  `maxLuggage` INT NULL,
  `comfort` INT NULL,
  `type` VARCHAR(45) NULL,
  `train_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carriage_train1_idx` (`train_id` ASC) VISIBLE,
  CONSTRAINT `fk_carriage_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `TrainSystem`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainSystem`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainSystem`.`passenger` (
  `id` INT NOT NULL,
  `min_comfort` VARCHAR(45) NULL,
  `human_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passenger_human1_idx` (`human_id` ASC) VISIBLE,
  CONSTRAINT `fk_passenger_human1`
    FOREIGN KEY (`human_id`)
    REFERENCES `TrainSystem`.`human` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainSystem`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainSystem`.`trip` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `train_id` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trip_train1_idx` (`train_id` ASC) VISIBLE,
  INDEX `fk_trip_passenger1_idx` (`passenger_id` ASC) VISIBLE,
  CONSTRAINT `fk_trip_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `TrainSystem`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trip_passenger1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `TrainSystem`.`passenger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainSystem`.`luggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainSystem`.`luggage` (
  `id` INT NOT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `weight` INT NULL,
  `passenger_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_luggage_passenger1_idx` (`passenger_id` ASC) VISIBLE,
  CONSTRAINT `fk_luggage_passenger1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `TrainSystem`.`passenger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
